// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABRa__NDhSqgfun5q6rxNJyZ-hvZ6PjPw',
    appId: '1:573905738738:web:8bf52d2ef50c82b96ca96b',
    messagingSenderId: '573905738738',
    projectId: 'study-app-40af1',
    authDomain: 'study-app-40af1.firebaseapp.com',
    storageBucket: 'study-app-40af1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaE0-LKoGjBXhgYYYpkdkclYZbxrSjijo',
    appId: '1:573905738738:android:54873dacb4197a5f6ca96b',
    messagingSenderId: '573905738738',
    projectId: 'study-app-40af1',
    storageBucket: 'study-app-40af1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj1JV2jqqMhrfz-xCAXlL56KxUnPTZ6pE',
    appId: '1:573905738738:ios:7ea06c0e05939d4e6ca96b',
    messagingSenderId: '573905738738',
    projectId: 'study-app-40af1',
    storageBucket: 'study-app-40af1.appspot.com',
    iosClientId: '573905738738-h4drnnn5632o3aqum0fqskjn03162q6t.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj1JV2jqqMhrfz-xCAXlL56KxUnPTZ6pE',
    appId: '1:573905738738:ios:7ea06c0e05939d4e6ca96b',
    messagingSenderId: '573905738738',
    projectId: 'study-app-40af1',
    storageBucket: 'study-app-40af1.appspot.com',
    iosClientId: '573905738738-h4drnnn5632o3aqum0fqskjn03162q6t.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseApp',
  );
}
